spring:
  application:
    name: kotlin-echo


server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
